# MoveIt supplements the URDF velocity limits with conservative acceleration
# limits for trajectory time parameterization.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
