controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    robotiq_3f_position_controller:
      type: position_controllers/JointGroupPositionController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0

scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    speed_scaling_interface_name: ""
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0

robotiq_3f_position_controller:
  ros__parameters:
    joints:
      - robotiq_3f_finger_a_proximal_joint
      - robotiq_3f_finger_a_middle_joint
      - robotiq_3f_finger_a_distal_joint
      - robotiq_3f_finger_b_scissor_joint
      - robotiq_3f_finger_b_proximal_joint
      - robotiq_3f_finger_b_middle_joint
      - robotiq_3f_finger_b_distal_joint
      - robotiq_3f_finger_c_scissor_joint
      - robotiq_3f_finger_c_proximal_joint
      - robotiq_3f_finger_c_middle_joint
      - robotiq_3f_finger_c_distal_joint
